# Generated by Django 3.1.7 on 2021-03-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tia_django_api_app', '0004_auto_20210328_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dep_Pro_Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=9999)),
                ('profit', models.FloatField()),
            ],
            options={
                'db_table': 'dep_pro_profit',
            },
        ),
    ]
