# Generated by Django 3.1.7 on 2021-03-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tia_django_api_app', '0005_dep_pro_profit'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dep_pro_profit',
            index=models.Index(fields=['department'], name='dep_pro_pro_departm_44beee_idx'),
        ),
    ]
