# Generated by Django 3.1.7 on 2021-03-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tia_django_api_app', '0006_auto_20210328_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='dep_pro_profit',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
    ]
